hw14: Main.o VirtualMemory.o Disk.o
	g++ Main.o VirtualMemory.o Disk.o -o hw14

Main.o: Main.cpp
	g++ -c Main.cpp

VirtualMemory.o: VirtualMemory.cpp
	g++ -c VirtualMemory.cpp

Disk.o: Disk.cpp
	g++ -c Disk.cpp
